# Generated by Django 4.0.3 on 2022-03-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentinformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('Fathers_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
            ],
        ),
    ]
