# Generated by Django 4.0.3 on 2022-03-21 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinformation',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='studentinformation',
            old_name='mother_name',
            new_name='Mother_name',
        ),
        migrations.RenameField(
            model_name='studentinformation',
            old_name='phone_no',
            new_name='Phone_no',
        ),
        migrations.RenameField(
            model_name='studentinformation',
            old_name='student_name',
            new_name='Student_name',
        ),
    ]
